name: Maven central workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  maven:
    uses: folio-org/.github/.github/workflows/maven.yml@FOLIO-4126-extract-sonar
    # Only handle push events from the main branch or tags, to decrease PR noise
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push' || github.ref_type == 'tag'
    secrets: inherit
